### ISSUE TITLE
Unable to run development server locally

### ISSUE THREAD

**Issue by Barrylimarti** [RocketChat/Apps.AI.Codebase.Assistant#15]
There is no proper information on how to run server locally with specific versions and steps involved. Although I tried running it locally with the steps given in Readme but facing issues while running npm run dev.

<img width="1207" alt="Screenshot 2024-09-27 at 1 07 35 AM" src="https://github.com/user-attachments/assets/c5b7c8f0-09c0-41e9-a32e-081e1113d485">

System:
MacOS 14.4.1 M3 Pro

Node version:
22.9.0

**Comment by preeesha** [comment]
@Barrylimarti You are using `ai-assistant` directory to run the `dev` command which is not valid. The directory contains code for RC app and cannot be run directly.

This command is for the `ingestion` directory.
